# Generated by Django 5.1.4 on 2024-12-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(null=True, upload_to='playlists/')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(choices=[(0, 'НЕОПУБЛИКОВАННЫЙ'), (1, 'ОПУБЛИКОВАННЫЙ')], default=0)),
                ('tracks', models.ManyToManyField(blank=True, related_name='playlists', to='musicapp.musictrack')),
            ],
            options={
                'ordering': ['-time_created'],
                'indexes': [models.Index(fields=['-time_created'], name='musicapp_pl_time_cr_8b8132_idx')],
            },
        ),
    ]
